# Sync submodule
# from: https://stackoverflow.com/a/67059629
name: sync notes

on:
  repository_dispatch:
    types: [publish]

  # Enable manually run workflow
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  sync:
    name: Auto sync submodules
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 1
        repo-token: ${{ secrets.MY_WORKFLOW_TOKEN }}
    - name: Update 'MyNotes' Submodule
      run: git submodule update --remote --recursive content/post

    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Change
        repo-token: ${{ secrets.MY_WORKFLOW_TOKEN }}
