# Sync submodule
# from: https://stackoverflow.com/a/67059629

on:
  repository_dispatch:
    types: [publish]

  # Enable manually run workflow
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  sync:
    name: Auto sync submodules
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 1

    - name: Update 'MyNotes' submodule
      run: git submodule update --remote --recursive content/post

    - name: Auto Commit
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
